clone_folder: C:\gopath\src\github.com\ironman-project\ironman
shallow_clone: true # for startup speed

environment:
  GOPATH: C:\gopath
  GOOS: windows 
  GOARCH: amd64
  CGO_ENABLED: 1
  GO111MODULE: on
  
stack: go 1.11

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\tools\mingw64\bin;%PATH%
  - choco install mingw
  - go version
  - go env

test_script:
  - go fmt ./...
  - go vet ./...
  - go test -v ./... -cover -bench . -race
  
build_script:
  - go build -o build/dist/windows/ironman.exe

deploy: false

