version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\ironman-project\ironman
shallow_clone: true # for startup speed

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.9
  GOOS: windows 
  CGO_ENABLED: 0 
  GOARCH: amd64

init:
  - git config --global core.autocrlf input  

platform:
  - x64

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go get -u github.com/golang/dep/cmd/dep
  - go version
  - go env


test_script:
  - dep ensure
  - go fmt ./...
  - go vet ./...
  - go test -v ./... -cover -bench . -race
  
build_script:
  - dep ensure
  - go build -o build/dist/windows/ironman.exe

deploy: false

