version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\ironman-project\ironman
shallow_clone: true # for startup speed

environment:
  GOPATH: C:\gopath
  GOOS: windows 
  CGO_ENABLED: 0 
  GOARCH: amd64
  

platform:
  - x64

# http://www.appveyor.com/docs/installed-software
install:
  # some helpful output for debugging builds
  - go version
  - go env
  # pre-installed MinGW at C:\MinGW is 32bit only
  # but MSYS2 at C:\msys64 has mingw64
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - gcc --version
  - g++ --version
  - go get -u github.com/golang/dep/cmd/dep


test_script:
  - set PATH=C:\gopath\bin;%PATH%
  - dep ensure
  - go fmt ./...
  - go vet ./...
  - go test -v ./... -cover -bench . -race
  
build_script:
  - go build -o build/dist/windows/ironman.exe

#artifacts:
#  - path: '%GOPATH%\bin\*.exe'
deploy: off