version: build-{build}.{branch}

clone_folder: C:\gopath\src\github.com\pkg\errors
shallow_clone: true # for startup speed

environment:
  GOPATH: C:\gopath

platform:
  - x64

# http://www.appveyor.com/docs/installed-software
install:
  # some helpful output for debugging builds
  - go version
  - go env
  # pre-installed MinGW at C:\MinGW is 32bit only
  # but MSYS2 at C:\msys64 has mingw64
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - gcc --version
  - g++ --version
  - go get -u github.com/golang/dep/cmd/dep


test_script:
  - set PATH=C:\gopath\bin;%PATH%
  - dep ensure
  - go fmt ./...
  - go vet ./...
  - go test -v ./... -cover -bench . -race
build_script:
  - GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "-X github.com/ironman-project/ironman/cmd.buildVersion=0.1.0 -X github.com/ironman-project/ironman/cmd.buildCommit=3f48780 -X github.com/ironman-project/ironman/cmd.buildDate=20180102.044021" -o build/dist/windows/ironman.exe

#artifacts:
#  - path: '%GOPATH%\bin\*.exe'
deploy: off